
services:
  postgres:
    image: postgres:14
    container_name: lakehouse_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lakehouse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  minio:
    image: minio/minio:latest
    container_name: lakehouse_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - lakehouse
  
  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/datalake --ignore-existing;
      mc mb myminio/warehouse --ignore-existing;
      exit 0;
      "
    networks:
      - lakehouse
  
  airflow-init:
    image: apache/airflow:2.8.1-python3.11
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_UID: ${AIRFLOW_UID:-50000}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'UKMzEm3yIuFYEq1y3-2FxPNWSVwRASpahmQ9kQfEr8E='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USER: 'admin'
      _AIRFLOW_WWW_USER_PASSWORD: 'admin'
      _PIP_ADDITIONAL_DEPENDENCIES: "psycopg2-binary boto3 pandas Flask-Session==0.5.0"
    volumes:
      - ../airflow:/opt/airflow
    networks:
      - lakehouse
    command: version

  
  airflow-webserver:
    image: apache/airflow:2.8.1-python3.11
    container_name: lakehouse_airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_UID: ${AIRFLOW_UID:-50000}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'UKMzEm3yIuFYEq1y3-2FxPNWSVwRASpahmQ9kQfEr8E='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _PIP_ADDITIONAL_DEPENDENCIES: "psycopg2-binary boto3 pandas Flask-Session==0.5.0"
    ports:
      - "8080:8080"
    volumes:
      - ../airflow:/opt/airflow
      - ../dbt:/opt/dbt
      - ../scripts:/opt/scripts
    networks:
      - lakehouse
    command: webserver


  airflow-scheduler:
    image: apache/airflow:2.8.1-python3.11
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_UID: ${AIRFLOW_UID:-50000}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'UKMzEm3yIuFYEq1y3-2FxPNWSVwRASpahmQ9kQfEr8E='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _PIP_ADDITIONAL_DEPENDENCIES: "psycopg2-binary boto3 pandas Flask-Session==0.5.0"
    volumes:
      - ../airflow:/opt/airflow
      - ../dbt:/opt/dbt
      - ../scripts:/opt/scripts
    networks:
      - lakehouse
    command: scheduler

  
  metabase:
    image: metabase/metabase:latest
    container_name: lakehouse_metabase
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: airflow
      MB_DB_PORT: 5432
      MB_DB_USER: airflow
      MB_DB_PASS: airflow
      MB_DB_HOST: postgres
    networks:
      - lakehouse
    volumes:
      - metabase_data:/metabase_data

volumes:
  postgres_data:
  minio_data:
  metabase_data:

networks:
  lakehouse:
    driver: bridge